AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template for S3 file uploads using pre-signed URLs for RojoPark"

Parameters:
  LambdaBucketName:
    Type: String
    Default: "rojo-park-lambda-bucket"
    Description: "S3 bucket to store Lambda deployment packages"

Resources:
  RojoImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "rojo-park-img-storage"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false 
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      CorsConfiguration: 
        CorsRules:
          - AllowedOrigins:
              - "*" 
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedHeaders:
              - "*"
            ExposedHeaders:
              - ETag
            MaxAge: 3000

  RojoImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RojoImageBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt RojoS3LambdaExecutionRole.Arn
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${RojoImageBucket}"
              - !Sub "arn:aws:s3:::${RojoImageBucket}/*"

          - Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${RojoImageBucket}/*"


  RojoS3LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RojoS3LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: RojoS3PresignedUrlAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${RojoImageBucket}"
                  - !Sub "arn:aws:s3:::${RojoImageBucket}/*"
              - Effect: Allow  # ✅ Allow CloudFormation to modify policies
                Action:
                  - s3:PutBucketPolicy
                Resource: !Sub "arn:aws:s3:::${RojoImageBucket}"
        - PolicyName: RojoCloudWatchLogsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  RojoGeneratePresignedUrlFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RojoGeneratePresignedUrlFunction
      Runtime: nodejs18.x
      Handler: index.handler
      Code:
        S3Bucket: !Ref LambdaBucketName
        S3Key: files/generate-presigned-url.zip
      Role: !GetAtt RojoS3LambdaExecutionRole.Arn
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref RojoImageBucket

  RojoS3ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RojoS3Api

  RojoPresignedUrlResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RojoS3ApiGateway.RootResourceId
      PathPart: get-presigned-url
      RestApiId: !Ref RojoS3ApiGateway

  RojoPresignedOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RojoS3ApiGateway
      ResourceId: !Ref RojoPresignedUrlResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          "application/json": "{\"statusCode\": 200}"
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST,PUT'"
              method.response.header.Access-Control-Allow-Headers: "'*'"
            ResponseTemplates:
              "application/json": ""
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: "'*'"
            method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST,PUT'"
            method.response.header.Access-Control-Allow-Headers: "'*'"

  RojoPresignedUrlMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RojoS3ApiGateway
      ResourceId: !Ref RojoPresignedUrlResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RojoGeneratePresignedUrlFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: "'*'"
            method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST,PUT'"
            method.response.header.Access-Control-Allow-Headers: "'*'"

  RojoS3ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RojoPresignedUrlMethod
    Properties:
      RestApiId: !Ref RojoS3ApiGateway
      StageName: prod

  RojoPresignedUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt RojoGeneratePresignedUrlFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RojoS3ApiGateway}/*"

Outputs:
  RojoPresignedUrlApi:
    Description: "API Endpoint to Get Pre-signed URL"
    Value: !Sub "https://${RojoS3ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/get-presigned-url"
